pipeline {
    agent any
    tools {
        maven 'maven'
    }
    stages {
        stage("clean up") {
            steps {
                deleteDir()
            }
        }
        stage("Clone repo") {
            steps {
                sh "git clone https://github.com/laffetnour/expl.spring.git"
            }
        }
        stage("Generate backend image") {
            steps {
                dir("expl.spring") {
                    sh "mvn clean install"
                    sh "docker build -t docexpl.spring ."
                }
            }
        }
        stage("Run docker compose") {
            steps {
                dir("expl.spring") {
                    sh "docker compose up -d"
                }
            }
        }
    }
}
